"""empty message

Revision ID: 93937f884e97
Revises: 
Create Date: 2026-04-10 18:43:41.273158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93937f884e97'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logic',
    sa.Column('reqd_id', sa.Integer(), nullable=False, comment='需求ID'),
    sa.Column('txt', sa.TEXT(), nullable=True, comment='逻辑文本'),
    sa.Column('filename', sa.String(length=256), nullable=True, comment='逻辑图文件名'),
    sa.Column('img_url', sa.String(length=256), nullable=True, comment='逻辑图'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logic_id'), 'logic', ['id'], unique=False)
    op.create_table('prod_user',
    sa.Column('user_id', sa.Integer(), nullable=True, comment='用户ID'),
    sa.Column('product_id', sa.Integer(), nullable=True, comment='产品ID'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'product_id')
    )
    op.create_index(op.f('ix_prod_user_id'), 'prod_user', ['id'], unique=False)
    op.create_table('req_rcm',
    sa.Column('req_id', sa.Integer(), nullable=False, comment='需求ID'),
    sa.Column('rcm_id', sa.Integer(), nullable=False, comment='RCMID'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('req_id', 'rcm_id')
    )
    op.create_index(op.f('ix_req_rcm_id'), 'req_rcm', ['id'], unique=False)
    op.create_table('srs_type',
    sa.Column('doc_id', sa.Integer(), nullable=False, comment='需求文档ID'),
    sa.Column('type_code', sa.String(length=64), nullable=False, comment='类型编号'),
    sa.Column('type_name', sa.String(length=64), nullable=False, comment='类型名称'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doc_id', 'type_code')
    )
    op.create_index(op.f('ix_srs_type_id'), 'srs_type', ['id'], unique=False)
    op.alter_column('cst', 'code',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               nullable=False,
               existing_comment='编号')
    op.alter_column('cst', 'category',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               existing_comment='分类',
               existing_nullable=True)
    op.alter_column('doc_file', 'category',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               existing_comment='类型',
               existing_nullable=True)
    op.alter_column('haz', 'code',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               nullable=False,
               existing_comment='编号')
    op.alter_column('haz', 'deal',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.TEXT(),
               existing_comment='处置',
               existing_nullable=True)
    op.alter_column('haz', 'rcms',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=1024),
               existing_comment='RCMS',
               existing_nullable=True)
    op.alter_column('haz', 'category',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               existing_comment='分类',
               existing_nullable=True)
    op.add_column('perm', sa.Column('priority', sa.Integer(), nullable=True, comment='权限优先级'))
    op.alter_column('perm', 'name',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               existing_comment='权限名',
               existing_nullable=True)
    op.add_column('prod_haz', sa.Column('situation', sa.String(length=256), nullable=True, comment='发生情况'))
    op.add_column('prod_haz', sa.Column('damage', sa.String(length=256), nullable=True, comment='伤害'))
    op.add_column('prod_haz', sa.Column('deal', sa.TEXT(), nullable=True, comment='处置'))
    op.add_column('prod_haz', sa.Column('init_rate', sa.SmallInteger(), nullable=True, comment='初始风险概率'))
    op.add_column('prod_haz', sa.Column('init_degree', sa.String(length=64), nullable=True, comment='初始危害程度'))
    op.add_column('prod_haz', sa.Column('init_level', sa.String(length=64), nullable=True, comment='初始风险水平'))
    op.add_column('prod_haz', sa.Column('cur_rate', sa.SmallInteger(), nullable=True, comment='初始风险概率'))
    op.add_column('prod_haz', sa.Column('cur_degree', sa.String(length=64), nullable=True, comment='初始危害程度'))
    op.add_column('prod_haz', sa.Column('cur_level', sa.String(length=64), nullable=True, comment='初始风险水平'))
    op.add_column('prod_haz', sa.Column('rcms', sa.String(length=1024), nullable=True, comment='RCMS'))
    op.add_column('prod_haz', sa.Column('evidence', sa.String(length=256), nullable=True, comment='证据'))
    op.add_column('product', sa.Column('project_id', sa.Integer(), nullable=True, comment='项目ID'))
    op.add_column('product', sa.Column('product_code', sa.String(length=256), nullable=True, comment='产品代码'))
    op.add_column('product', sa.Column('create_user_id', sa.Integer(), nullable=True, comment='创建人ID'))
    op.alter_column('product', 'type_code',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=256),
               comment='型号',
               existing_comment='类型',
               existing_nullable=True)
    op.alter_column('product', 'full_version',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=256),
               existing_comment='完整版本',
               existing_nullable=False)
    op.alter_column('product', 'release_version',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=256),
               existing_comment='发布版本',
               existing_nullable=False)
    op.alter_column('product', 'udi',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=256),
               existing_comment='UDI',
               existing_nullable=True)
    op.alter_column('product', 'scope',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.TEXT(),
               existing_comment='试用范围',
               existing_nullable=True)
    op.alter_column('product', 'component',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.TEXT(),
               existing_comment='产品组成',
               existing_nullable=True)
    op.alter_column('product', 'note',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.TEXT(),
               existing_comment='备注',
               existing_nullable=True)
    op.drop_column('product', 'country')
    op.alter_column('project', 'name',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               existing_comment='用户账户',
               existing_nullable=True)
    op.alter_column('project', 'country',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               existing_comment='国家',
               existing_nullable=True)
    op.alter_column('rcm', 'code',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               nullable=False,
               existing_comment='编号')
    op.add_column('sds_doc', sa.Column('srsdoc_id', sa.Integer(), nullable=False, comment='SRS_DOC_ID'))
    op.add_column('sds_doc', sa.Column('file_no', sa.String(length=64), nullable=True, comment='文件编号'))
    op.drop_constraint('sds_doc_product_id_version_key', 'sds_doc', type_='unique')
    op.create_unique_constraint(None, 'sds_doc', ['srsdoc_id', 'version'])
    op.drop_column('sds_doc', 'product_id')
    op.add_column('sds_node', sa.Column('sds_code', sa.String(length=256), nullable=True, comment='设计编号'))
    op.add_column('sds_node', sa.Column('ref_type', sa.String(length=64), nullable=True, comment='引用类型'))
    op.add_column('sds_node', sa.Column('label', sa.TEXT(), nullable=True, comment='节点标签'))
    op.alter_column('sds_node', 'title',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=256),
               nullable=True,
               existing_comment='节点标题')
    op.alter_column('sds_node', 'text',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.TEXT(),
               nullable=True,
               existing_comment='节点文本')
    op.add_column('sds_reqd', sa.Column('doc_id', sa.Integer(), nullable=False, comment='文档ID'))
    op.add_column('sds_reqd', sa.Column('func_detail', sa.TEXT(), nullable=True, comment='功能'))
    op.alter_column('sds_reqd', 'overview',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.TEXT(),
               existing_comment='需求概述',
               existing_nullable=True)
    op.alter_column('sds_reqd', 'logic_txt',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.TEXT(),
               existing_comment='逻辑文本',
               existing_nullable=True)
    op.alter_column('sds_reqd', 'intput',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.TEXT(),
               existing_comment='输入',
               existing_nullable=True)
    op.alter_column('sds_reqd', 'output',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.TEXT(),
               existing_comment='输出',
               existing_nullable=True)
    op.alter_column('sds_reqd', 'interface',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.TEXT(),
               existing_comment='接口',
               existing_nullable=True)
    op.drop_constraint('sds_reqd_req_id_key', 'sds_reqd', type_='unique')
    op.create_unique_constraint(None, 'sds_reqd', ['doc_id', 'req_id'])
    op.drop_column('sds_reqd', 'logic_img')
    op.drop_column('sds_reqd', 'function')
    op.add_column('sds_trace', sa.Column('doc_id', sa.Integer(), nullable=False, comment='文档ID'))
    op.add_column('sds_trace', sa.Column('location', sa.String(length=256), nullable=True, comment='位置'))
    op.alter_column('sds_trace', 'sds_code',
               existing_type=sa.VARCHAR(length=256),
               nullable=True,
               existing_comment='设计编号')
    op.alter_column('sds_trace', 'chapter',
               existing_type=sa.VARCHAR(length=256),
               nullable=True,
               existing_comment='章节')
    op.create_unique_constraint(None, 'sds_trace', ['doc_id', 'req_id'])
    op.add_column('srs_doc', sa.Column('folder_name', sa.String(length=128), nullable=True, comment='文件夹名称'))
    op.add_column('srs_doc', sa.Column('file_no', sa.String(length=64), nullable=True, comment='文件编号'))
    op.add_column('srs_node', sa.Column('label', sa.TEXT(), nullable=True, comment='节点标签'))
    op.add_column('srs_node', sa.Column('srs_code', sa.String(length=64), nullable=True, comment='需求编号'))
    op.add_column('srs_node', sa.Column('rcm_codes', sa.String(length=1024), nullable=True, comment='RCM编码'))
    op.add_column('srs_node', sa.Column('ref_type', sa.String(length=64), nullable=True, comment='引用类型'))
    op.add_column('srs_node', sa.Column('img_url', sa.TEXT(), nullable=True, comment='图片URL'))
    op.alter_column('srs_node', 'title',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=256),
               nullable=True,
               existing_comment='节点标题')
    op.alter_column('srs_node', 'text',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.TEXT(),
               nullable=True,
               existing_comment='节点文本')
    op.drop_column('srs_node', 'rcm_code')
    op.add_column('srs_req', sa.Column('type_code', sa.String(length=64), nullable=False, comment='需求类型'))
    op.alter_column('srs_req', 'module',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=256),
               existing_comment='模块',
               existing_nullable=True)
    op.alter_column('srs_req', 'function',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=256),
               existing_comment='功能',
               existing_nullable=True)
    op.alter_column('srs_req', 'sub_function',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=256),
               existing_comment='子功能',
               existing_nullable=True)
    op.alter_column('srs_req', 'location',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=256),
               existing_comment='位置',
               existing_nullable=True)
    op.drop_constraint('srs_req_doc_id_code_key', 'srs_req', type_='unique')
    op.create_unique_constraint(None, 'srs_req', ['doc_id', 'type_code', 'code'])
    op.drop_column('srs_req', 'req_type')
    op.add_column('srs_reqd', sa.Column('name', sa.String(length=256), nullable=True, comment='需求名称'))
    op.alter_column('srs_reqd', 'overview',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.TEXT(),
               existing_comment='需求概述',
               existing_nullable=True)
    op.alter_column('srs_reqd', 'pre_condition',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.TEXT(),
               existing_comment='前置条件',
               existing_nullable=True)
    op.alter_column('srs_reqd', 'trigger',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.TEXT(),
               existing_comment='触发条件',
               existing_nullable=True)
    op.alter_column('srs_reqd', 'work_flow',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.TEXT(),
               existing_comment='工作流程',
               existing_nullable=True)
    op.alter_column('srs_reqd', 'post_condition',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.TEXT(),
               existing_comment='后置条件',
               existing_nullable=True)
    op.alter_column('srs_reqd', 'exception',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.TEXT(),
               existing_comment='异常情况',
               existing_nullable=True)
    op.alter_column('srs_reqd', 'constraint',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.TEXT(),
               existing_comment='约束',
               existing_nullable=True)
    op.drop_column('srs_reqd', 'rcm_codes')
    op.alter_column('test_case', 'code',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               existing_comment='用例编号',
               existing_nullable=True)
    op.alter_column('test_case', 'srs_code',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               existing_comment='需求编号',
               existing_nullable=True)
    op.alter_column('test_case', 'function',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.TEXT(),
               existing_comment='功能点',
               existing_nullable=True)
    op.alter_column('test_case', 'description',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.TEXT(),
               existing_comment='描述',
               existing_nullable=True)
    op.alter_column('test_case', 'precondition',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.TEXT(),
               existing_comment='前置条件',
               existing_nullable=True)
    op.alter_column('test_case', 'test_step',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.TEXT(),
               existing_comment='测试步骤',
               existing_nullable=True)
    op.alter_column('test_case', 'expect',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.TEXT(),
               existing_comment='预期结果',
               existing_nullable=True)
    op.alter_column('test_case', 'note',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.TEXT(),
               existing_comment='备注',
               existing_nullable=True)
    op.alter_column('usr', 'name',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               existing_comment='用户账户',
               existing_nullable=True)
    op.alter_column('usr', 'pwd',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               existing_comment='密码',
               existing_nullable=True)
    op.alter_column('usr', 'pwd_sk',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               existing_comment='密码盐',
               existing_nullable=True)
    op.alter_column('usr', 'nick_name',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               existing_comment='姓名',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usr', 'nick_name',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               existing_comment='姓名',
               existing_nullable=True)
    op.alter_column('usr', 'pwd_sk',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               existing_comment='密码盐',
               existing_nullable=True)
    op.alter_column('usr', 'pwd',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               existing_comment='密码',
               existing_nullable=True)
    op.alter_column('usr', 'name',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               existing_comment='用户账户',
               existing_nullable=True)
    op.alter_column('test_case', 'note',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(length=256),
               existing_comment='备注',
               existing_nullable=True)
    op.alter_column('test_case', 'expect',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(length=256),
               existing_comment='预期结果',
               existing_nullable=True)
    op.alter_column('test_case', 'test_step',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(length=256),
               existing_comment='测试步骤',
               existing_nullable=True)
    op.alter_column('test_case', 'precondition',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(length=256),
               existing_comment='前置条件',
               existing_nullable=True)
    op.alter_column('test_case', 'description',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(length=256),
               existing_comment='描述',
               existing_nullable=True)
    op.alter_column('test_case', 'function',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(length=256),
               existing_comment='功能点',
               existing_nullable=True)
    op.alter_column('test_case', 'srs_code',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               existing_comment='需求编号',
               existing_nullable=True)
    op.alter_column('test_case', 'code',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               existing_comment='用例编号',
               existing_nullable=True)
    op.add_column('srs_reqd', sa.Column('rcm_codes', sa.VARCHAR(length=256), autoincrement=False, nullable=True, comment='RCM编号'))
    op.alter_column('srs_reqd', 'constraint',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(length=256),
               existing_comment='约束',
               existing_nullable=True)
    op.alter_column('srs_reqd', 'exception',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(length=256),
               existing_comment='异常情况',
               existing_nullable=True)
    op.alter_column('srs_reqd', 'post_condition',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(length=256),
               existing_comment='后置条件',
               existing_nullable=True)
    op.alter_column('srs_reqd', 'work_flow',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(length=256),
               existing_comment='工作流程',
               existing_nullable=True)
    op.alter_column('srs_reqd', 'trigger',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(length=256),
               existing_comment='触发条件',
               existing_nullable=True)
    op.alter_column('srs_reqd', 'pre_condition',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(length=256),
               existing_comment='前置条件',
               existing_nullable=True)
    op.alter_column('srs_reqd', 'overview',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(length=256),
               existing_comment='需求概述',
               existing_nullable=True)
    op.drop_column('srs_reqd', 'name')
    op.add_column('srs_req', sa.Column('req_type', sa.SMALLINT(), autoincrement=False, nullable=False, comment='需求类型'))
    op.drop_constraint(None, 'srs_req', type_='unique')
    op.create_unique_constraint('srs_req_doc_id_code_key', 'srs_req', ['doc_id', 'code'])
    op.alter_column('srs_req', 'location',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=64),
               existing_comment='位置',
               existing_nullable=True)
    op.alter_column('srs_req', 'sub_function',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=64),
               existing_comment='子功能',
               existing_nullable=True)
    op.alter_column('srs_req', 'function',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=64),
               existing_comment='功能',
               existing_nullable=True)
    op.alter_column('srs_req', 'module',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=64),
               existing_comment='模块',
               existing_nullable=True)
    op.drop_column('srs_req', 'type_code')
    op.add_column('srs_node', sa.Column('rcm_code', sa.VARCHAR(length=64), autoincrement=False, nullable=True, comment='RCM编码'))
    op.alter_column('srs_node', 'text',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(length=256),
               nullable=False,
               existing_comment='节点文本')
    op.alter_column('srs_node', 'title',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=64),
               nullable=False,
               existing_comment='节点标题')
    op.drop_column('srs_node', 'img_url')
    op.drop_column('srs_node', 'ref_type')
    op.drop_column('srs_node', 'rcm_codes')
    op.drop_column('srs_node', 'srs_code')
    op.drop_column('srs_node', 'label')
    op.drop_column('srs_doc', 'file_no')
    op.drop_column('srs_doc', 'folder_name')
    op.drop_constraint(None, 'sds_trace', type_='unique')
    op.alter_column('sds_trace', 'chapter',
               existing_type=sa.VARCHAR(length=256),
               nullable=False,
               existing_comment='章节')
    op.alter_column('sds_trace', 'sds_code',
               existing_type=sa.VARCHAR(length=256),
               nullable=False,
               existing_comment='设计编号')
    op.drop_column('sds_trace', 'location')
    op.drop_column('sds_trace', 'doc_id')
    op.add_column('sds_reqd', sa.Column('function', sa.VARCHAR(length=256), autoincrement=False, nullable=True, comment='功能'))
    op.add_column('sds_reqd', sa.Column('logic_img', sa.VARCHAR(length=256), autoincrement=False, nullable=True, comment='逻辑图'))
    op.drop_constraint(None, 'sds_reqd', type_='unique')
    op.create_unique_constraint('sds_reqd_req_id_key', 'sds_reqd', ['req_id'])
    op.alter_column('sds_reqd', 'interface',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(length=256),
               existing_comment='接口',
               existing_nullable=True)
    op.alter_column('sds_reqd', 'output',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(length=256),
               existing_comment='输出',
               existing_nullable=True)
    op.alter_column('sds_reqd', 'intput',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(length=256),
               existing_comment='输入',
               existing_nullable=True)
    op.alter_column('sds_reqd', 'logic_txt',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(length=256),
               existing_comment='逻辑文本',
               existing_nullable=True)
    op.alter_column('sds_reqd', 'overview',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(length=256),
               existing_comment='需求概述',
               existing_nullable=True)
    op.drop_column('sds_reqd', 'func_detail')
    op.drop_column('sds_reqd', 'doc_id')
    op.alter_column('sds_node', 'text',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(length=256),
               nullable=False,
               existing_comment='节点文本')
    op.alter_column('sds_node', 'title',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=64),
               nullable=False,
               existing_comment='节点标题')
    op.drop_column('sds_node', 'label')
    op.drop_column('sds_node', 'ref_type')
    op.drop_column('sds_node', 'sds_code')
    op.add_column('sds_doc', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='产品ID'))
    op.drop_constraint(None, 'sds_doc', type_='unique')
    op.create_unique_constraint('sds_doc_product_id_version_key', 'sds_doc', ['product_id', 'version'])
    op.drop_column('sds_doc', 'file_no')
    op.drop_column('sds_doc', 'srsdoc_id')
    op.alter_column('rcm', 'code',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               nullable=True,
               existing_comment='编号')
    op.alter_column('project', 'country',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               existing_comment='国家',
               existing_nullable=True)
    op.alter_column('project', 'name',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               existing_comment='用户账户',
               existing_nullable=True)
    op.add_column('product', sa.Column('country', sa.VARCHAR(length=256), autoincrement=False, nullable=True, comment='国家'))
    op.alter_column('product', 'note',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(length=256),
               existing_comment='备注',
               existing_nullable=True)
    op.alter_column('product', 'component',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(length=32),
               existing_comment='产品组成',
               existing_nullable=True)
    op.alter_column('product', 'scope',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(length=32),
               existing_comment='试用范围',
               existing_nullable=True)
    op.alter_column('product', 'udi',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=32),
               existing_comment='UDI',
               existing_nullable=True)
    op.alter_column('product', 'release_version',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=32),
               existing_comment='发布版本',
               existing_nullable=False)
    op.alter_column('product', 'full_version',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=32),
               existing_comment='完整版本',
               existing_nullable=False)
    op.alter_column('product', 'type_code',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=32),
               comment='类型',
               existing_comment='型号',
               existing_nullable=True)
    op.drop_column('product', 'create_user_id')
    op.drop_column('product', 'product_code')
    op.drop_column('product', 'project_id')
    op.drop_column('prod_haz', 'evidence')
    op.drop_column('prod_haz', 'rcms')
    op.drop_column('prod_haz', 'cur_level')
    op.drop_column('prod_haz', 'cur_degree')
    op.drop_column('prod_haz', 'cur_rate')
    op.drop_column('prod_haz', 'init_level')
    op.drop_column('prod_haz', 'init_degree')
    op.drop_column('prod_haz', 'init_rate')
    op.drop_column('prod_haz', 'deal')
    op.drop_column('prod_haz', 'damage')
    op.drop_column('prod_haz', 'situation')
    op.alter_column('perm', 'name',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               existing_comment='权限名',
               existing_nullable=True)
    op.drop_column('perm', 'priority')
    op.alter_column('haz', 'category',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               existing_comment='分类',
               existing_nullable=True)
    op.alter_column('haz', 'rcms',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=256),
               existing_comment='RCMS',
               existing_nullable=True)
    op.alter_column('haz', 'deal',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(length=256),
               existing_comment='处置',
               existing_nullable=True)
    op.alter_column('haz', 'code',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               nullable=True,
               existing_comment='编号')
    op.alter_column('doc_file', 'category',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               existing_comment='类型',
               existing_nullable=True)
    op.alter_column('cst', 'category',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               existing_comment='分类',
               existing_nullable=True)
    op.alter_column('cst', 'code',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               nullable=True,
               existing_comment='编号')
    op.drop_index(op.f('ix_srs_type_id'), table_name='srs_type')
    op.drop_table('srs_type')
    op.drop_index(op.f('ix_req_rcm_id'), table_name='req_rcm')
    op.drop_table('req_rcm')
    op.drop_index(op.f('ix_prod_user_id'), table_name='prod_user')
    op.drop_table('prod_user')
    op.drop_index(op.f('ix_logic_id'), table_name='logic')
    op.drop_table('logic')
    # ### end Alembic commands ###
