logging:
  version: 1
  disable_existing_loggers: False
  formatters:
    default:
      format: "%(asctime)s %(levelname)s [%(filename)s.%(lineno)s]: %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      formatter: default
      stream: ext://sys.stdout
    app:
      class: logging.handlers.TimedRotatingFileHandler
      level: INFO
      formatter: default
      encoding: "utf8"
      filename: logs/app.log
      when: "midnight"
      interval: 1
      backupCount: 30
    api:
      class: logging.handlers.TimedRotatingFileHandler
      level: INFO
      formatter: default
      encoding: "utf8"
      filename: logs/api.log
      when: "midnight"
      interval: 1
      backupCount: 30
  loggers:
    src.api:
      level: INFO
      propagate: no
      handlers: [api]
  root:
    level: INFO
    handlers: [console, app]
